version: "3"
services:
  app:
    container_name: line_echo_bot_app
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/home/node/app
    ports:
      - "8080:3000"


    
